name: build-java-docker
    
inputs:
  username:
    description: docker username
    required: true
  password:
    description: docker password
    required: true
  working-directory:
    description: working directory
    required: false

runs:
  using: composite
  steps:
  - uses: actions/checkout@v2
  - name: Set up JDK 11
    uses: actions/setup-java@v2
    with:
      java-version: '11'
      distribution: 'adopt'
      cache: maven
  - name: Build with Maven
    working-directory: ${{ inputs.working-directory }}
    run: mvn -B -DskipTests package --file pom.xml
    shell: bash
    
  - name: Build Image and Push
    uses: mr-smithers-excellent/docker-build-push@v5
    with:
      image: faissalelfid/${{ inputs.working-directory }}
      tags: 0.0.1
      directory: ${{ inputs.working-directory }}
#       dockerfile: Dockerfile
      registry: docker.io
      username: ${{ inputs.username }}
      password: ${{ inputs.password }}
      dockerfile: ${{ inputs.working-directory }}/Dockerfile
